// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsULbW_2t7njK4gvOL9pqaaT_jrSCnCnA',
    appId: '1:825979790819:web:e721e3e5ff894e37f22cd6',
    messagingSenderId: '825979790819',
    projectId: 'spotify0121',
    authDomain: 'spotify0121.firebaseapp.com',
    storageBucket: 'spotify0121.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOMo-x7oqd9uSQ_9_YsDFdXMIKiZPSlc',
    appId: '1:825979790819:android:a3625ce24d65fa6af22cd6',
    messagingSenderId: '825979790819',
    projectId: 'spotify0121',
    storageBucket: 'spotify0121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAssYvvoIKbr5YUAYpvGCFJM3tkoDCj66U',
    appId: '1:825979790819:ios:9943a55ecd2b2317f22cd6',
    messagingSenderId: '825979790819',
    projectId: 'spotify0121',
    storageBucket: 'spotify0121.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAssYvvoIKbr5YUAYpvGCFJM3tkoDCj66U',
    appId: '1:825979790819:ios:9943a55ecd2b2317f22cd6',
    messagingSenderId: '825979790819',
    projectId: 'spotify0121',
    storageBucket: 'spotify0121.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsULbW_2t7njK4gvOL9pqaaT_jrSCnCnA',
    appId: '1:825979790819:web:f693a153a0462c32f22cd6',
    messagingSenderId: '825979790819',
    projectId: 'spotify0121',
    authDomain: 'spotify0121.firebaseapp.com',
    storageBucket: 'spotify0121.appspot.com',
  );
}
